# Generated by Django 4.0.3 on 2022-03-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter device name', max_length=60, verbose_name='Device name')),
                ('device_image', models.ImageField(blank=True, null=True, upload_to='static/assets/img', verbose_name='Device Image')),
                ('frequency_1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequency 1')),
                ('frequency_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequency 2')),
                ('frequency_3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequency 3')),
                ('frequency_4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequency 4')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Description')),
                ('enable', models.BooleanField(default=False, verbose_name='Activate')),
                ('remote_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ip adresss')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Release date')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
