# Generated by Django 4.0.3 on 2022-03-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='enable',
            field=models.BooleanField(blank=True, default=False, verbose_name='Activate'),
        ),
    ]
