# Generated by Django 4.0.3 on 2022-03-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='frequency_5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequency 5'),
        ),
        migrations.AddField(
            model_name='device',
            name='frequency_6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequency 6'),
        ),
        migrations.AddField(
            model_name='device',
            name='frequency_7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequency 7'),
        ),
        migrations.AddField(
            model_name='device',
            name='frequency_8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Frequency 8'),
        ),
    ]
