# Generated by Django 3.2.12 on 2022-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220331_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevices',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='userdevices',
            name='device_images',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/img'),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
    ]
