# Generated by Django 3.2.12 on 2022-03-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220331_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevices',
            name='device_images',
        ),
        migrations.CreateModel(
            name='UserDetailsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_images', models.ImageField(blank=True, null=True, upload_to='static/assets/img')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdevices')),
            ],
        ),
    ]
