# Generated by Django 3.2.12 on 2022-03-31 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220331_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevices',
            name='user_detail',
        ),
    ]
