# Generated by Django 3.2.12 on 2022-03-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userdevices_user_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevices',
            name='user_detail',
        ),
    ]
