# Generated by Django 3.2.12 on 2022-04-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userdevices_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevices',
            name='lane1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='lane1_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='lane2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='lane2_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='lane3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='lane3_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='lane4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='lane4_status',
            field=models.BooleanField(default=False),
        ),
    ]
