# Generated by Django 3.2.12 on 2022-04-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220404_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevices',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
