# Generated by Django 3.2.12 on 2022-04-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notificationchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
